/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Logica.Cartelera;
import Logica.Collector;
import Logica.Peliculas;
import datos.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Collator;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AUXSISTEMAS
 */
public class FrCarteleraEdit extends javax.swing.JFrame {

    String HoraPromo = "2017-10-21 12:00:00";
    Conexion ObjCon = new Conexion();
    Calendar objCalendario = Calendar.getInstance();
    Calendar ObjCalendarios = new GregorianCalendar();
    DateFormat dateFormat = new SimpleDateFormat("hh:mm:ss");
    int Id;
    int IdSala;
    int IdPelicula;
    int Activa;
    int AplicaProm;

    /**
     * Creates new form FrCartelera
     */
    public FrCarteleraEdit() {
        initComponents();
        CargarCartelera();
        CargarComboPel();
        CargarComboSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTpAsiento2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        tlabelcartelera = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxNroSala = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxIdPelicula = new javax.swing.JComboBox<>();
        ChkActivaSi = new javax.swing.JCheckBox();
        ChkAplicapSi = new javax.swing.JCheckBox();
        bntGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        cbxTpAsiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTpAsiento2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SALA #", "HORA APERTURA", "PELICULA", "DURACION", "APLICA PROM", "ACTIVA", "SILLAS DISP.", "SILLAS PREF. DISP", "TEC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarteleraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCartelera);

        tlabelcartelera.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        tlabelcartelera.setText(" ADMON CARTELERA");

        jLabel3.setText("Sala:");

        jLabel4.setText("ACTIVA:");

        jLabel6.setText("PELICULA   :");

        jLabel7.setText("APLICA PROM :");

        cbxNroSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNroSalaActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CineColombia.png"))); // NOI18N

        cbxIdPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdPeliculaActionPerformed(evt);
            }
        });

        bntGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\src\\IMAGENES\\GUARDAR.PNG")); // NOI18N
        bntGuardar.setText("GUARDAR");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ATRAZ.png"))); // NOI18N
        jButton1.setText("VOLVER AL MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tlabelcartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(bntGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNroSala, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChkAplicapSi)
                            .addComponent(ChkActivaSi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tlabelcartelera)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxNroSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxIdPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ChkAplicapSi))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ChkActivaSi))
                .addGap(38, 38, 38)
                .addComponent(bntGuardar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNroSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNroSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNroSalaActionPerformed

    //obtiene el evento click del mouse en la tabla y le asignamos los valores a los campos.
    private void tblCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarteleraMouseClicked
        try {
            int row = tblCartelera.getSelectedRow();
            int Act = 0;
            int AplPro = 0;
            Id = (int) tblCartelera.getValueAt(row, 0);
            PreparedStatement ps = ObjCon.abrir().prepareStatement("SELECT IdCartelera ,cartelera.IdSala ,cartelera.IdPelicula as IdPelicula,if(AplicaProm>0,'SI','NO') as AplicaProm,if(Activa >0,'SI','NO') as Activa,NroSala ,Capacidad ,HoraApertura,Tecnologia ,Nombre , Duracion , Categoria,(Capacidad - (CantOcupadaSala + AsientosPref)) as CantOcupadaSala,AsientosPref \n"
                    + "FROM `cartelera` \n"
                    + "LEFT JOIN salascn ON salascn.IdSala = cartelera.IdSala\n"
                    + "LEFT JOIN peliculas ON peliculas.IdPelicula = cartelera.IdPelicula\n"
                    + "WHERE IdCartelera=" + Id);
            ResultSet rs = ObjCon.ejecutarSP(ps); //Ejecutar procedimiento almacenado o vista
            ObjCon.cerrar();
            //LLenamos la variable con la consulta.
            while (rs.next()) {
                if (tblCartelera.getValueAt(row, 6).equals("SI")) {
                    Act = 1;
                }
                if (tblCartelera.getValueAt(row, 5).equals("SI")) {
                    AplPro = 1;
                }
                cbxNroSala.setSelectedItem("#" + tblCartelera.getValueAt(row, 1));
                cbxIdPelicula.setSelectedItem(rs.getInt(3)+"-"+tblCartelera.getValueAt(row, 3));
                if (Act >= 1) {
                    ChkActivaSi.setSelected(true);
                } else {
                    ChkActivaSi.setSelected(false);
                }
                if (AplPro >= 1) {
                    ChkAplicapSi.setSelected(true);
                } else {
                    ChkAplicapSi.setSelected(false);
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tblCarteleraMouseClicked

    /**
     * Des:Carga el combo de las peliculas.
     */
    public void CargarComboPel() {
        Peliculas objPeliculas = new Peliculas();
        objPeliculas.listar();
        for (Peliculas m : Collector.listaPeliculas) {
            cbxIdPelicula.addItem(m.getIdPelicula()+"-"+m.getNombre());
        }
    }

    /**
     * Des:LLena el combo de las salas.
     */
    public void CargarComboSala() {
        try {
            ArrayList<String> Salas = new ArrayList<String>();
            PreparedStatement ps = ObjCon.abrir().prepareStatement("select IdSala,NroSala from salascn");
            ResultSet rs = ObjCon.ejecutarSP(ps); //Ejecutar procedimiento almacenado o vista

            //Mientras existan filas (rs.next())
            while (rs.next()) {
                //Agregar a la Colección de Objetos
                Salas.add(rs.getString(1)+"-#" + rs.getString(2));
            }
            Iterator<String> ContSalas = Salas.iterator();
            while (ContSalas.hasNext()) {
                cbxNroSala.addItem(ContSalas.next());
            }

        } catch (Exception e) {

        }
    }

    public int ObtenerPel(String Peli) {
        String[] arr = Peli.split("-");
        String Var = arr[0];
        int IdPel = Integer.parseInt(Var);
        return IdPel;
    }

    public int ObtenerSala(String Sala) {
        String[] arr = Sala.split("-");
        String Var = arr[0];
        int IdPel = Integer.parseInt(Var);
        return IdPel;
    }
    private void cbxIdPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIdPeliculaActionPerformed

    private void cbxTpAsiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTpAsiento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTpAsiento2ActionPerformed

    /**
     * Des:Captura el evento click dentro de la tabla para llenar los datos.
     *
     * @param evt
     */
    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        int ValIdSala = ObtenerSala((String) cbxNroSala.getSelectedItem());
        int ValIdPel = IdPelicula = ObtenerPel((String) cbxIdPelicula.getSelectedItem());
        int ValAct =0;
        int ValAplProm =0;
        if(ChkActivaSi.isSelected()){
            ValAct = 1;
        }
        else{
            ValAct = 0;
        }
        if(ChkAplicapSi.isSelected()){
            ValAplProm = 1;
        }
        else{
            ValAplProm = 0;
        }
        Cartelera ObjCart = new Cartelera();
        ObjCart.setIdSala(ValIdSala);
        ObjCart.setIdPelicula(ValIdPel);
        ObjCart.setAplicaProm(Integer.toString(ValAplProm));
        ObjCart.setActiva(Integer.toString(ValAct));
        ObjCart.setIdCartelera(Id);
        ObjCart.actualizar();
        CargarCartelera();
    }//GEN-LAST:event_bntGuardarActionPerformed

    /**
     * Des:Devuelve al menu principal y cierra la ventana actual.
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrInicio ObjInicio = new FrInicio();
        ObjInicio.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Des:Metodo para cargar la tabla cartelera.
     */
    public void CargarCartelera() {
        Cartelera ObjCartelera = new Cartelera();
        ObjCartelera.listar(2);
        //Limpiamos todas las filas de la tabla
        ((DefaultTableModel) tblCartelera.getModel()).setRowCount(0);

        //Creamos variable para las columnas
        Object obj[] = new Object[10];

        for (Cartelera p : Collector.ListaCartelera) {
            //Asignamos valor a cada columna
            obj[0] = p.getIdCartelera();
            obj[1] = p.getNroSala();
            obj[2] = p.getHoraApertura();
            obj[3] = p.getNombre();
            obj[4] = p.getDuracion();
            obj[5] = p.getAplicaProm();
            obj[6] = p.getActiva();
            obj[7] = p.getCantOcupadaSala();
            obj[8] = p.getAsientosPref();
            obj[9] = p.getTecnologia();

            //Agregamos las nuevas filas
            ((DefaultTableModel) tblCartelera.getModel()).addRow(obj);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkActivaSi;
    private javax.swing.JCheckBox ChkAplicapSi;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JComboBox<String> cbxIdPelicula;
    private javax.swing.JComboBox<String> cbxNroSala;
    private javax.swing.JComboBox<String> cbxTpAsiento2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JLabel tlabelcartelera;
    // End of variables declaration//GEN-END:variables
}
