/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Logica.Cartelera;
import Logica.Collector;
import Logica.Peliculas;
import datos.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Collator;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AUXSISTEMAS
 */
public class FrCartelera extends javax.swing.JFrame {

    String HoraPromo = "2017-10-21 12:00:00";
    Conexion ObjCon = new Conexion();
    Calendar objCalendario = Calendar.getInstance();
    Calendar ObjCalendarios = new GregorianCalendar();
    DateFormat dateFormat = new SimpleDateFormat("hh:mm:ss");

    /**
     * Creates new form FrCartelera
     */
    public FrCartelera() {
        initComponents();
        CargarCartelera();
        cbxTpAsiento.addItem("GENERAL");
        cbxTpAsiento.addItem("PREFERENCIAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartelera = new javax.swing.JTable();
        tlabelcartelera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdCartelera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPelicula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxTpAsiento = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SALA #", "HORA APERTURA", "PELICULA", "DURACION", "APLICA PROM", "ACTIVA", "SILLAS DISP.", "SILLAS PREF. DISP", "TEC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarteleraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCartelera);

        tlabelcartelera.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        tlabelcartelera.setText("CARTELERA");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/BANER_CARTELERA.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FACTURACIÓN");

        jLabel3.setText("ID :");

        jLabel4.setText("CANTIDAD : ");

        jLabel5.setText("CLIENTE    :");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMPRIMIR.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CANCELAR.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("PELICULA   :");

        jLabel7.setText("TIPO ASIENTO :");

        cbxTpAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTpAsientoActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CineColombia.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ATRAZ.png"))); // NOI18N
        jButton1.setText("VOLVER AL MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tlabelcartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTpAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel8)
                                .addGap(112, 112, 112)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlabelcartelera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxTpAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtPelicula.setText("");
        txtCantidad.setText("");
        txtCliente.setText("");
        txtIdCartelera.setText("");
        txtIdCartelera.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxTpAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTpAsientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTpAsientoActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    /**
     * Des: Imprime la factura de la pelicula seleccionada.
     *
     * @param evt
     */
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        try {
            String Hora = "2017-10-21 " + ObjCalendarios.get(Calendar.HOUR_OF_DAY) + ":" + ObjCalendarios.get(Calendar.MINUTE) + ":00";
            int Cont, IdPel, Sala = 0, Cant = 0, Id = 0, SillasDisp = 0, SillasDispPref = 0, idSala = 0,Cont2;
            double Valor = 0;
            boolean ValAct;
            String AplicaPromo = "NO";
            String HoraFuncion = "", Tecno = "", Promo = "", NombrePel = "";
            Cartelera ObjCart = new Cartelera();
            java.util.Date fecha = new Date();
            Object Val = cbxTpAsiento.getSelectedItem();
            String TpAsiento = (String) Val;
            String NombreCli = txtCliente.getText();
            int DifHoras = DiferenciaFechas(Hora, HoraPromo);
            //JOptionPane.showMessageDialog(null, DifHoras);
            PreparedStatement ps = ObjCon.abrir().prepareStatement("SELECT IdCartelera ,cartelera.IdSala ,cartelera.IdPelicula ,if(AplicaProm>0,'SI','NO') as AplicaProm,if(Activa >0,'SI','NO') as Activa,NroSala ,Capacidad ,HoraApertura,Tecnologia ,Nombre , Duracion , Categoria,(Capacidad - (CantOcupadaSala + AsientosPref)) as CantOcupadaSala,AsientosPref \n"
                    + "FROM `cartelera` \n"
                    + "LEFT JOIN salascn ON salascn.IdSala = cartelera.IdSala\n"
                    + "LEFT JOIN peliculas ON peliculas.IdPelicula = cartelera.IdPelicula\n"
                    + "WHERE IdCartelera=" + txtIdCartelera.getText());
            ResultSet rs = ObjCon.ejecutarSP(ps); //Ejecutar procedimiento almacenado o vista
            ObjCon.cerrar();
            //LLenamos la variable con la consulta.
            while (rs.next()) {
                idSala = Integer.parseInt(rs.getString(2));
                NombrePel = rs.getString(10);
                Tecno = rs.getString(9);
                HoraFuncion = rs.getString(8);
                Sala = Integer.parseInt(rs.getString(6));
                Promo = rs.getString(4);
                IdPel = Integer.parseInt(rs.getString(3));
                SillasDisp = Integer.parseInt(rs.getString(13));
                SillasDispPref = Integer.parseInt(rs.getString(14));
            }
            Cont = Integer.parseInt(txtCantidad.getText());
            Cont2 = Integer.parseInt(txtCantidad.getText());
            //Valida las cantidades de sillas preferenciales.
            if (TpAsiento.equals("PREFERENCIAL") && SillasDispPref < Cont) {
                JOptionPane.showMessageDialog(null, "NO HAY LA CANTIDAD DE SILLAS PREFERENCIALES PARA TU COMPRA.");
                txtCantidad.requestFocus();
            } else if (SillasDisp >= Cont || SillasDispPref >= Cont) {
                
                if (SillasDisp >= Cont) {
                    //Validamos si la compra aplica para promocion.
                    if (Promo.equals("SI") && Cont == 2 && DifHoras >= 0) {
                        if (Tecno.equals("2D") && TpAsiento.equals("GENERAL") || TpAsiento.equals("PREFERENCIAL")) {
                            Valor = 6000;
                        } else if (Tecno.equals("3D") && TpAsiento.equals("PREFERENCIAL")) {
                            Valor = 10000;
                        } else if (Tecno.equals("3D") && TpAsiento.equals("GENERAL")) {
                            Valor = 8000;
                        }
                        //Si aplica promo le restamos 1 al contador para que imprima una sola factura.
                        Cont = Cont - 1;
                        AplicaPromo = "SI";
                    } else if (Tecno.equals("3D") && TpAsiento.equals("GENERAL")) {
                        Valor = 8000;
                    } else if (Tecno.equals("3D") && TpAsiento.equals("PREFERENCIAL")) {
                        Valor = 10000;
                    } else if (Tecno.equals("2D")) {
                        Valor = 6000;
                    }
                    if (TpAsiento.equals("PREFERENCIAL")) {
                        ValAct = ObjCart.actualizarSalas(Integer.toString(Cont2), Integer.toString(Cont2), idSala);
                    } else {
                        ValAct = ObjCart.actualizarSalas(Integer.toString(Cont2), "0", idSala);
                    }
                    for (int i = 0; i < Cont; i++) {

                        if (ValAct == true) {
                            JOptionPane.showMessageDialog(null, "----------------------------------------------------------------------------------------------------------\n"
                                    + "                        Cine Colombia                                       \n"
                                    + "                       NIT 89087668-08                                      \n"
                                    + " Pelicula                                                                   \n"
                                    + "" + NombrePel + "            " + Tecno + "       " + TpAsiento + "             \n"
                                    + "Sala#:" + Sala + "                                                           \n"
                                    + "Hora Función:" + HoraFuncion + "                                            \n"
                                    + "Valor:" + Valor + "                                                         \n "
                                    + "Cliente:" + NombreCli + "                           " + AplicaPromo + " Promo\n"
                                    + "                                            Compra :" + fecha + "           \n"
                                    + "                       www.cinecolombia.com.co                              \n"
                                    + "\"----------------------------------------------------------------------------------------------------------\n");

                        } else {
                            JOptionPane.showMessageDialog(null, "ALGO SALIO MAL EN LA CONSULTA.");
                        }
                    }
                    btnCancelar.doClick();
                    CargarCartelera();
                }
                else if(SillasDispPref>= Cont && TpAsiento.equals("PREFERENCIAL")){
                    //Validamos si la compra aplica para promocion.
                    if (Promo.equals("SI") && Cont == 2 && DifHoras >= 0) {
                        if (Tecno.equals("2D") && TpAsiento.equals("GENERAL") || TpAsiento.equals("PREFERENCIAL")) {
                            Valor = 6000;
                        } else if (Tecno.equals("3D") && TpAsiento.equals("PREFERENCIAL")) {
                            Valor = 10000;
                        } else if (Tecno.equals("3D") && TpAsiento.equals("GENERAL")) {
                            Valor = 8000;
                        }
                        //Si aplica promo le restamos 1 al contador para que imprima una sola factura.
                        Cont = Cont - 1;
                        AplicaPromo = "SI";
                    } else if (Tecno.equals("3D") && TpAsiento.equals("GENERAL")) {
                        Valor = 8000;
                    } else if (Tecno.equals("3D") && TpAsiento.equals("PREFERENCIAL")) {
                        Valor = 10000;
                    } else if (Tecno.equals("2D")) {
                        Valor = 6000;
                    }
                    if (TpAsiento.equals("PREFERENCIAL")) {
                        ValAct = ObjCart.actualizarSalas(Integer.toString(Cont), Integer.toString(Cont), idSala);
                    } else {
                        ValAct = ObjCart.actualizarSalas(Integer.toString(Cont), "0", idSala);
                    }
                    for (int i = 0; i < Cont; i++) {

                        if (ValAct == true) {
                            JOptionPane.showMessageDialog(null, "-------------------------------------------------------------\n"
                                    + "                        Cine Colombia                                       \n"
                                    + "                       NIT 89087668-08                                      \n"
                                    + " Pelicula                                                                   \n"
                                    + "" + NombrePel + "            " + Tecno + "       " + TpAsiento + "             \n"
                                    + "Sala#:" + Sala + "                                                           \n"
                                    + "Hora Función:" + HoraFuncion + "                                            \n"
                                    + "Valor:" + Valor + "                                                         \n "
                                    + "Cliente:" + NombreCli + "                           " + AplicaPromo + " Promo\n"
                                    + "                                            Compra :" + fecha + "           \n"
                                    + "                       www.cinecolombia.com.co                              \n"
                                    + "\"-------------------------------------------------------------\\n\"");

                        } else {
                            JOptionPane.showMessageDialog(null, "ALGO SALIO MAL EN LA CONSULTA.");
                        }
                    }
                    btnCancelar.doClick();
                    CargarCartelera();
                }
                else{
                    JOptionPane.showMessageDialog(null, "LO SENTIMOS NO HAY SILLAS DISPONIBLES.");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "NO HAY LA CANTIDAD DE SILLAS SUFICIENTES PARA TU COMPRA.");
                txtCantidad.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR :" + e);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed
    //obtiene el evento click del mouse en la tabla y le asignamos los valores a los campos.
    private void tblCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarteleraMouseClicked
        int row = tblCartelera.getSelectedRow();//Obtenemos la fila clikeada
        int IdPel;
        String Nombre;
        Nombre = (String) tblCartelera.getValueAt(row, 3);//Obtenemos el valor de la columna de la fila sel.
        IdPel = (int) tblCartelera.getValueAt(row, 0);
        txtIdCartelera.setText(Integer.toString(IdPel));
        txtPelicula.setText(Nombre);
        txtCantidad.requestFocus();
    }//GEN-LAST:event_tblCarteleraMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrInicio ObjInicio =new FrInicio();
        ObjInicio.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void CargarCartelera() {
        Cartelera ObjCartelera = new Cartelera();
        ObjCartelera.listar(1);
        //Limpiamos todas las filas de la tabla
        ((DefaultTableModel) tblCartelera.getModel()).setRowCount(0);

        //Creamos variable para las columnas
        Object obj[] = new Object[10];

        for (Cartelera p : Collector.ListaCartelera) {
            //Asignamos valor a cada columna
            obj[0] = p.getIdCartelera();
            obj[1] = p.getNroSala();
            obj[2] = p.getHoraApertura();
            obj[3] = p.getNombre();
            obj[4] = p.getDuracion();
            obj[5] = p.getAplicaProm();
            obj[6] = p.getActiva();
            obj[7] = p.getCantOcupadaSala();
            obj[8] = p.getAsientosPref();
            obj[9] = p.getTecnologia();

            //Agregamos las nuevas filas
            ((DefaultTableModel) tblCartelera.getModel()).addRow(obj);
        }
    }

    /**
     * Des: Retorna la diferencia de horas entre 2
     *
     * @param vinicio
     * @param vfinal
     * @return
     */
    public static int DiferenciaFechas(String vinicio, String vfinal) {

        Date dinicio = null, dfinal = null;
        long milis1, milis2, diff;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        try {
            // PARSEO STRING A DATE
            dinicio = sdf.parse(vinicio);
            dfinal = sdf.parse(vfinal);

        } catch (ParseException e) {

            System.out.println("Se ha producido un error en el parseo");
        }

        //INSTANCIA DEL CALENDARIO GREGORIANO
        Calendar cinicio = Calendar.getInstance();
        Calendar cfinal = Calendar.getInstance();

        //ESTABLECEMOS LA FECHA DEL CALENDARIO CON EL DATE GENERADO ANTERIORMENTE
        cinicio.setTime(dinicio);
        cfinal.setTime(dfinal);

        milis1 = cinicio.getTimeInMillis();

        milis2 = cfinal.getTimeInMillis();

        diff = milis2 - milis1;

        // calcular la diferencia en segundos
        long diffSegundos = Math.abs(diff / 1000);

        // calcular la diferencia en minutos
        long diffMinutos = Math.abs(diff / (60 * 1000));

        long restominutos = diffMinutos % 60;

        // calcular la diferencia en horas
        long diffHoras = (diff / (60 * 60 * 1000));

        // calcular la diferencia en dias
        long diffdias = Math.abs(diff / (24 * 60 * 60 * 1000));


        /*
        System.out.println("En segundos: " + diffSegundos + " segundos.");

        System.out.println("En minutos: " + diffMinutos + " minutos.");

        System.out.println("En horas: " + diffHoras + " horas.");

        System.out.println("En dias: " + diffdias + " dias.");
         */
        int devolver = (int) (diffHoras);

        return devolver;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbxTpAsiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCartelera;
    private javax.swing.JLabel tlabelcartelera;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIdCartelera;
    private javax.swing.JTextField txtPelicula;
    // End of variables declaration//GEN-END:variables
}
