/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Logica.Categorias;
import Logica.Collector;
import Logica.Peliculas;
import java.time.Duration;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AUXSISTEMAS
 */
public class FrPeliculas extends javax.swing.JFrame {
     private int id = 0;
    /**
     * Creates new form FrPeliculas
     */
    public FrPeliculas() {
        initComponents();
        CargarGategorias();
        CargarPeliculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPeliculas = new javax.swing.JTable();
        cbxCategorias = new javax.swing.JComboBox<>();
        bntGuardar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("NOMBRE       :");

        jLabel2.setText("CATEGORIA :");

        jLabel3.setText("DURACIÓN  :");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        try {
            txtDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "DURACION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblPeliculas);

        cbxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriasActionPerformed(evt);
            }
        });

        bntGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\src\\IMAGENES\\GUARDAR.PNG")); // NOI18N
        bntGuardar.setText("GUARDAR");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });

        bntEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\src\\IMAGENES\\EDITAR.png")); // NOI18N
        bntEditar.setText("EDITAR");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\imagenes\\ELIMINAR.PNG")); // NOI18N
        bntEliminar.setText("ELIMINAR");
        bntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\imagenes\\CANCELAR.png")); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\AUXSISTEMAS\\Documents\\NetBeansProjects\\CineFinal\\imagenes\\CineColombia.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("ADMINISTRACIÓN DE PELICULAS");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ATRAZ.png"))); // NOI18N
        jButton1.setText("VOLVER AL MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxCategorias, 0, 330, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(bntGuardar)
                            .addGap(45, 45, 45)
                            .addComponent(bntEditar)
                            .addGap(42, 42, 42)
                            .addComponent(bntEliminar)
                            .addGap(43, 43, 43)
                            .addComponent(btnCancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGuardar)
                    .addComponent(bntEditar)
                    .addComponent(bntEliminar)
                    .addComponent(btnCancelar))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        // TODO add your handling code here:                                
        //Obtener la fila seleccionada
        int fila = TblPeliculas.getSelectedRow();

        //Si es mayor o igual a cero, entonces, existe fila.
        if (fila >= 0) {
            //Instanciamos el objeto Producto
            Peliculas objPel = new Peliculas();
            //Asignamos valor al id
            objPel.setIdPelicula(Integer.parseInt(TblPeliculas.getValueAt(fila, 0).toString()));
            if(objPel.PeliculaEnCartelera()==true){
               objPel.eliminar(); //Ejecutamos el método eliminar del objeto
            }
            else{
               JOptionPane.showMessageDialog(null,"NO SE PUEDE ELIMINAR LA PELICULA YA QUE SE ENCUENTRA EN CARTELERA.");
            }

            //Refrescamos la lista de productos
            CargarPeliculas();
        }
    }//GEN-LAST:event_bntEliminarActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        //Obtener la fila seleccionada
        int fila = TblPeliculas.getSelectedRow();

        //Si es mayor o igual a cero, entonces, existe fila.
        if (fila >= 0) {
            //Asignamos valores de la tabla a cada control o variables
            id = Integer.parseInt(TblPeliculas.getValueAt(fila, 0).toString());
            txtNombre.setText(TblPeliculas.getValueAt(fila, 1).toString());
            cbxCategorias.setSelectedItem(TblPeliculas.getValueAt(fila, 2)); //Indicamos que "item" se debe seleccionar
            txtDuracion.setText(TblPeliculas.getValueAt(fila, 3).toString());
        }
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
       //Creamos el objeto Producto
        Peliculas objPel= new Peliculas();
        Object Val = cbxCategorias.getSelectedItem();
        String NmCat = (String) Val;
        //Asignamos valor a cada una de sus propiedades
        objPel.setCategoria(NmCat); //Obtener el nombre de la categoria
        objPel.setNombre(txtNombre.getText());
        objPel.setDuracion((txtDuracion.getText()));

        //Realizamos una validación: si el "ID" es "cero", entonces "registramos" el producto
        if (id == 0) {
            objPel.registrar();
        } else {
            //Caso contrario, asignamos valor al "ID" de la pelicula para poder "actualizar"
            objPel.setIdPelicula(id);
            objPel.actualizar();
        }

        //Refrescamos la lista de productos
        CargarPeliculas();

        //auto-ejecutamos el limpiar
        btnCancelar.doClick();
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //Limpiamos los controles y variables
        cbxCategorias.setSelectedIndex(0);
        txtNombre.setText("");
        txtDuracion.setText("");
        id = 0;

        //Enviamos el enfoque al control
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        FrInicio ObjInicio =new FrInicio();
        ObjInicio.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CargarGategorias(){
        //Para "listar" Marcas, debemos crear un Objeto del mismo
        Categorias objCategoria = new Categorias();
        objCategoria.listar(); //Invocar al método listar del Objeto
        //Ese método de arriba permite llenar datos en el Colector

        //Recorremos el objeto Marca en la Colección (listaMarcas)
        for (Categorias m : Collector.listaCategorias) {
            cbxCategorias.addItem(m.getNmCategoria()); //Agregamos al comboBox
        }
    }
    
    public void CargarPeliculas(){
        Peliculas ObjPeliculas = new Peliculas();
        ObjPeliculas.listar();
        //Limpiamos todas las filas de la tabla
        ((DefaultTableModel) TblPeliculas.getModel()).setRowCount(0);
        
        //Creamos variable para las columnas
        Object obj[] = new Object[4];
         
        for (Peliculas p : Collector.listaPeliculas) {
            //Asignamos valor a cada columna
            obj[0] = p.getIdPelicula();
            obj[1] = p.getNombre();
            obj[2] = p.getCategoria();
            obj[3] = p.getDuracion();

            //Agregamos las nuevas filas
            ((DefaultTableModel) TblPeliculas.getModel()).addRow(obj);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPeliculas;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
